/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceprintRouteImport } from './routes/voiceprint'
import { Route as VoiceTrustRouteImport } from './routes/voice-trust'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as RuralRouteImport } from './routes/rural'
import { Route as RangeRouteImport } from './routes/range'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as ContinuousRouteImport } from './routes/continuous'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CallRouteImport } from './routes/call'
import { Route as IndexRouteImport } from './routes/index'

const VoiceprintRoute = VoiceprintRouteImport.update({
  id: '/voiceprint',
  path: '/voiceprint',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceTrustRoute = VoiceTrustRouteImport.update({
  id: '/voice-trust',
  path: '/voice-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralRoute = RuralRouteImport.update({
  id: '/rural',
  path: '/rural',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuousRoute = ContinuousRouteImport.update({
  id: '/continuous',
  path: '/continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/continuous': typeof ContinuousRoute
  '/helpdesk': typeof HelpdeskRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/onboarding': typeof OnboardingRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/safeguarding': typeof SafeguardingRoute
  '/treasury': typeof TreasuryRoute
  '/verify': typeof VerifyRoute
  '/voice-trust': typeof VoiceTrustRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/continuous': typeof ContinuousRoute
  '/helpdesk': typeof HelpdeskRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/onboarding': typeof OnboardingRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/safeguarding': typeof SafeguardingRoute
  '/treasury': typeof TreasuryRoute
  '/verify': typeof VerifyRoute
  '/voice-trust': typeof VoiceTrustRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/continuous': typeof ContinuousRoute
  '/helpdesk': typeof HelpdeskRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/onboarding': typeof OnboardingRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/safeguarding': typeof SafeguardingRoute
  '/treasury': typeof TreasuryRoute
  '/verify': typeof VerifyRoute
  '/voice-trust': typeof VoiceTrustRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/campaign'
    | '/continuous'
    | '/helpdesk'
    | '/languages'
    | '/mitra'
    | '/onboarding'
    | '/range'
    | '/rural'
    | '/safeguarding'
    | '/treasury'
    | '/verify'
    | '/voice-trust'
    | '/voiceprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/campaign'
    | '/continuous'
    | '/helpdesk'
    | '/languages'
    | '/mitra'
    | '/onboarding'
    | '/range'
    | '/rural'
    | '/safeguarding'
    | '/treasury'
    | '/verify'
    | '/voice-trust'
    | '/voiceprint'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/campaign'
    | '/continuous'
    | '/helpdesk'
    | '/languages'
    | '/mitra'
    | '/onboarding'
    | '/range'
    | '/rural'
    | '/safeguarding'
    | '/treasury'
    | '/verify'
    | '/voice-trust'
    | '/voiceprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  CampaignRoute: typeof CampaignRoute
  ContinuousRoute: typeof ContinuousRoute
  HelpdeskRoute: typeof HelpdeskRoute
  LanguagesRoute: typeof LanguagesRoute
  MitraRoute: typeof MitraRoute
  OnboardingRoute: typeof OnboardingRoute
  RangeRoute: typeof RangeRoute
  RuralRoute: typeof RuralRoute
  SafeguardingRoute: typeof SafeguardingRoute
  TreasuryRoute: typeof TreasuryRoute
  VerifyRoute: typeof VerifyRoute
  VoiceTrustRoute: typeof VoiceTrustRoute
  VoiceprintRoute: typeof VoiceprintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voiceprint': {
      id: '/voiceprint'
      path: '/voiceprint'
      fullPath: '/voiceprint'
      preLoaderRoute: typeof VoiceprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-trust': {
      id: '/voice-trust'
      path: '/voice-trust'
      fullPath: '/voice-trust'
      preLoaderRoute: typeof VoiceTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural': {
      id: '/rural'
      path: '/rural'
      fullPath: '/rural'
      preLoaderRoute: typeof RuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuous': {
      id: '/continuous'
      path: '/continuous'
      fullPath: '/continuous'
      preLoaderRoute: typeof ContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  CampaignRoute: CampaignRoute,
  ContinuousRoute: ContinuousRoute,
  HelpdeskRoute: HelpdeskRoute,
  LanguagesRoute: LanguagesRoute,
  MitraRoute: MitraRoute,
  OnboardingRoute: OnboardingRoute,
  RangeRoute: RangeRoute,
  RuralRoute: RuralRoute,
  SafeguardingRoute: SafeguardingRoute,
  TreasuryRoute: TreasuryRoute,
  VerifyRoute: VerifyRoute,
  VoiceTrustRoute: VoiceTrustRoute,
  VoiceprintRoute: VoiceprintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
