/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceprintRouteImport } from './routes/voiceprint'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RuralRouteImport } from './routes/rural'
import { Route as RangeRouteImport } from './routes/range'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CallRouteImport } from './routes/call'
import { Route as IndexRouteImport } from './routes/index'

const VoiceprintRoute = VoiceprintRouteImport.update({
  id: '/voiceprint',
  path: '/voiceprint',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralRoute = RuralRouteImport.update({
  id: '/rural',
  path: '/rural',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/verify': typeof VerifyRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/verify': typeof VerifyRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/campaign': typeof CampaignRoute
  '/languages': typeof LanguagesRoute
  '/mitra': typeof MitraRoute
  '/range': typeof RangeRoute
  '/rural': typeof RuralRoute
  '/verify': typeof VerifyRoute
  '/voiceprint': typeof VoiceprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/campaign'
    | '/languages'
    | '/mitra'
    | '/range'
    | '/rural'
    | '/verify'
    | '/voiceprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/campaign'
    | '/languages'
    | '/mitra'
    | '/range'
    | '/rural'
    | '/verify'
    | '/voiceprint'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/campaign'
    | '/languages'
    | '/mitra'
    | '/range'
    | '/rural'
    | '/verify'
    | '/voiceprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  CampaignRoute: typeof CampaignRoute
  LanguagesRoute: typeof LanguagesRoute
  MitraRoute: typeof MitraRoute
  RangeRoute: typeof RangeRoute
  RuralRoute: typeof RuralRoute
  VerifyRoute: typeof VerifyRoute
  VoiceprintRoute: typeof VoiceprintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voiceprint': {
      id: '/voiceprint'
      path: '/voiceprint'
      fullPath: '/voiceprint'
      preLoaderRoute: typeof VoiceprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural': {
      id: '/rural'
      path: '/rural'
      fullPath: '/rural'
      preLoaderRoute: typeof RuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  CampaignRoute: CampaignRoute,
  LanguagesRoute: LanguagesRoute,
  MitraRoute: MitraRoute,
  RangeRoute: RangeRoute,
  RuralRoute: RuralRoute,
  VerifyRoute: VerifyRoute,
  VoiceprintRoute: VoiceprintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
